### ISSUE TITLE
Dead kernel

### ISSUE THREAD

**Issue by rainsworth** [aardk/jupyter-casa#8]
Hello! Thank you for your work on this!

I am trying to use your jupyter-casa image to create my own notebook for reducing my data with CASA. I have attempted to open a Casa notebook using both the Singularity and Docker images, and in both cases I get the following error (although for different complaints): 

"Dead kernel: The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened."

# Docker
In the case of **Docker**, I follow the instructions on your README after pulling penngwyn/jupytercasa (below is the output from my mac terminal but I have also tried using a linux machine and get the same error, let me know if you would like to see that also):

```
Rachaels-MacBook-Pro:jupyter-casa rachael$ docker run --rm -p 8888:8888 -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -v PATH_TO_DATA_DIR:/Users/rachael/Desktop/jupyter-casa/examples penngwyn/jupytercasa /bin/sh -c "jupyter notebook"
[I 14:36:49.733 NotebookApp] Writing notebook server cookie secret to /home/jupyter/.local/share/jupyter/runtime/notebook_cookie_secret
[W 14:36:49.932 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 14:36:49.937 NotebookApp] Serving notebooks from local directory: /home/jupyter
[I 14:36:49.937 NotebookApp] 0 active kernels
[I 14:36:49.937 NotebookApp] The Jupyter Notebook is running at:
[I 14:36:49.938 NotebookApp] http://[all ip addresses on your system]:8888/?token=7d9487a3ff9ac6471a22b9733816fc4a299fea1b4d1779c9
[I 14:36:49.938 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:36:49.938 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=7d9487a3ff9ac6471a22b9733816fc4a299fea1b4d1779c9
```

I copy and past the link into Firefox and get the Jupyter server no problem:

<img width="1474" alt="screen shot 2018-05-15 at 15 38 15" src="https://user-images.githubusercontent.com/10600877/40064339-353a4138-5857-11e8-9436-c9b7bb095efb.png">

I then click ```New``` -> ```Notebook``` -> ```Casa``` and get the dead kernal error after it tries to restart several times:

<img width="1472" alt="screen shot 2018-05-15 at 15 39 07" src="https://user-images.githubusercontent.com/10600877/40064340-35641d1e-5857-11e8-988f-122e209db05b.png">

I get the following errors in the terminal:

```
[I 14:37:06.348 NotebookApp] 302 GET /?token=7d9487a3ff9ac6471a22b9733816fc4a299fea1b4d1779c9 (172.17.0.1) 0.73ms
[I 14:39:07.706 NotebookApp] Creating new notebook in 
[I 14:39:07.721 NotebookApp] Writing notebook-signing key to /home/jupyter/.local/share/jupyter/notebook_secret
[I 14:39:08.378 NotebookApp] Kernel started: 57e8ad11-2b62-46cd-a70b-dfb61710c9b3
__init__
__main__
setgpid( ) failed: Operation not permitted
                   processes may be left dangling...
CASA Version 5.1.1-5  -REL (r40000)
  Compiled on: Mon 2018/01/15 13:35:54 UTC
show_console = False
casalogger: cannot connect to X server /private/tmp/com.apple.launchd.##########/org.macosforge.xquartz:0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/casapy/__main__.py", line 7, in <module>
    from .casapy import *
  File "/usr/local/lib/python2.7/dist-packages/casapy/casapy.py", line 1282, in <module>
    pl.clf( )
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 665, in clf
    gcf().clf()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 578, in gcf
    return figure()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "/private/tmp/com.apple.launchd.##########/org.macosforge.xquartz:0"
```

...which repeats 5x in attempt to restart...

```
[W 14:39:23.415 NotebookApp] KernelRestarter: restart failed
[W 14:39:23.416 NotebookApp] Kernel 57e8ad11-2b62-46cd-a70b-dfb61710c9b3 died, removing from map.
ERROR:root:kernel 57e8ad11-2b62-46cd-a70b-dfb61710c9b3 restarted failed!
[W 14:39:23.437 NotebookApp] 410 DELETE /api/sessions/1de79fee-9c79-47fe-9a23-b6d9651b26b5 (172.17.0.1): Kernel deleted before session
[W 14:39:23.438 NotebookApp] Kernel deleted before session
[W 14:39:23.438 NotebookApp] 410 DELETE /api/sessions/1de79fee-9c79-47fe-9a23-b6d9651b26b5 (172.17.0.1) 2.17ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=casapy
[I 14:41:08.511 NotebookApp] Saving file at /Untitled.ipynb
```

# Singularity

In the case of Singularity, I follow the instructions on your README after pulling jupyter-casa.simg (using a linux machine):

```
rainswor@lofar8 /raid/scratch/rainswor/eMERLIN/emerlin-casa-jupyter > singularity run jupyter-casa.simg
Starting Jupyter
[I 15:12:36.922 NotebookApp] Serving notebooks from local directory: /home/rainswor
[I 15:12:36.922 NotebookApp] 0 active kernels
[I 15:12:36.922 NotebookApp] The Jupyter Notebook is running at:
[I 15:12:36.922 NotebookApp] http://localhost:8888/?token=51985082174bcc713fc13692b25dc94ec96f43799c7f5965
[I 15:12:36.922 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:12:36.939 NotebookApp] No web browser found: could not locate runnable browser.
[C 15:12:36.940 NotebookApp]
   
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=51985082174bcc713fc13692b25dc94ec96f43799c7f5965
```

Copy link into Firefox, again get the Jupyter server no problem, but click ```New``` -> ```Notebook``` -> ```Casa``` and get the same dead kernal error after it tries to restart several times. However, get the following different error in the terminal:

```
[I 15:13:13.725 NotebookApp] 302 GET /tree?token=44b0ab545c790ed5f1f503aef05c938da6d6bf3393f5e635 (::1) 4.40ms
[I 15:13:19.570 NotebookApp] 302 GET /?token=51985082174bcc713fc13692b25dc94ec96f43799c7f5965 (::1) 0.84ms
[I 15:13:31.613 NotebookApp] Creating new notebook in
[I 15:13:33.655 NotebookApp] Kernel started: 50713164-5f74-4794-83ee-c200e4e03f87
__init__
__main__
[W 15:13:33.745 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180515151236 (::1) 69.96ms referer=http://localhost:8888/notebooks/Untitled5.ipynb?kernel_name=casapy
setgpid( ) failed: Operation not permitted
                   processes may be left dangling...
CASA Version 5.1.1-5  -REL (r40000)
  Compiled on: Mon 2018/01/15 13:35:54 UTC
2018-05-15 15:13:38    WARN    MeasIERS::findTab (file /usr/local/casa/casacore/measures/Measures/MeasIERS.cc, line 381)    Requested data table Observatories cannot be found in the searched directories:
2018-05-15 15:13:38    WARN    MeasIERS::findTab (file /usr/local/casa/casacore/measures/Measures/MeasIERS.cc, line 381)+    /raid/scratch//
2018-05-15 15:13:38    SEVERE    MeasTable::initObservatories() (file /usr/local/casa/casacore/measures/Measures/MeasTable.cc, line 2910)    Cannot read table of Observatories
2018-05-15 15:13:38    SEVERE        Exception Reported: 2018-05-15 15:13:38    SEVERE    MeasTable::initObservatories() (file /usr/local/casa/casacore/measures/Measures/MeasTable.cc, line 2910)    Cannot read table of Observatories
2018-05-15 15:13:38    WARN    MeasIERS::findTab (file /usr/local/casa/casacore/measures/Measures/MeasIERS.cc, line 381)    Requested data table Observatories cannot be found in the searched directories:
2018-05-15 15:13:38    WARN    MeasIERS::findTab (file /usr/local/casa/casacore/measures/Measures/MeasIERS.cc, line 381)+    /raid/scratch//
2018-05-15 15:13:38    SEVERE    MeasTable::initObservatories() (file /usr/local/casa/casacore/measures/Measures/MeasTable.cc, line 2910)    Cannot read table of Observatories
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/casapy/__main__.py", line 7, in <module>
    from .casapy import *
  File "/usr/local/lib/python2.7/dist-packages/casapy/casapy.py", line 437, in <module>
    from taskinit import *
  File "/usr/local/casa/linux64/lib/python2.7/taskinit.py", line 204, in <module>
    im,cb,ms,tb,me,ia,po,sm,cl,cs,rg,sl,dc,vp,msmd,fi,fn,imd,sdms,lm,at=gentools()
  File "/usr/local/casa/linux64/lib/python2.7/taskinit.py", line 202, in gentools
    return tuple([eval(tooldic[reqtool]) for reqtool in reqtools])
  File "<string>", line 1, in <module>
  File "/usr/local/casa/linux64/lib/python2.7/__casac__/vpmanager.py", line 106, in __init__
    this = _vpmanager.new_vpmanager()
RuntimeError: 2018-05-15 15:13:38    SEVERE    MeasTable::initObservatories() (file /usr/local/casa/casacore/measures/Measures/MeasTable.cc, line 2910)    Cannot read table of Observatories
```

...which repeats 5x in attempt to restart...

```
[W 15:13:51.702 NotebookApp] KernelRestarter: restart failed
[W 15:13:51.703 NotebookApp] Kernel 50713164-5f74-4794-83ee-c200e4e03f87 died, removing from map.
ERROR:root:kernel 50713164-5f74-4794-83ee-c200e4e03f87 restarted failed!
[W 15:13:51.762 NotebookApp] 410 DELETE /api/sessions/f11d5879-d270-4107-84a5-5c02c2a17238 (::1): Kernel deleted before session
[W 15:13:51.762 NotebookApp] Kernel deleted before session
[W 15:13:51.763 NotebookApp] 410 DELETE /api/sessions/f11d5879-d270-4107-84a5-5c02c2a17238 (::1) 6.30ms referer=http://localhost:8888/notebooks/Untitled5.ipynb?kernel_name=casapy
[I 15:15:33.638 NotebookApp] Saving file at /Untitled5.ipynb
```

---

So in the case of Docker it dies because it cannot connect to X server (although I believe I followed the instructions for sharing the local X11 socket with the Docker container) and in the case of Singularity it dies because it cannot read table of observatories. 

Help?

**Comment by rainsworth** [comment]
Docker update for mac:

Followed this blog post: https://fredrikaverpil.github.io/2016/07/31/docker-for-mac-and-gui-applications/ and was able to open a Casa notebook without the Dead kernel error. The CASA logger also opened in an Xquartz window (is it expected?). The only problem seems to be that the local data directory has not been copied to the Docker container so I am unable to test any CASA tasks.

<img width="1637" alt="screen shot 2018-05-16 at 15 57 06" src="https://user-images.githubusercontent.com/10600877/40125049-d33476ae-5921-11e8-9471-3e1d360490aa.png">


```
Rachaels-MacBook-Pro:data rachael$ open -a XQuartz
Rachaels-MacBook-Pro:data rachael$ ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
Rachaels-MacBook-Pro:data rachael$ xhost + $ip
##.###.###.### being added to access control list
Rachaels-MacBook-Pro:data rachael$ docker run --rm -p 8888:8888 -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$ip:0 -v PATH_TO_DATA_DIR:/Users/rachael/Desktop/emerlin-casa-jupyter/data penngwyn/jupytercasa /bin/sh -c "jupyter notebook"
[I 14:46:48.276 NotebookApp] Writing notebook server cookie secret to /home/jupyter/.local/share/jupyter/runtime/notebook_cookie_secret
[W 14:46:48.459 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 14:46:48.466 NotebookApp] Serving notebooks from local directory: /home/jupyter
[I 14:46:48.467 NotebookApp] 0 active kernels
[I 14:46:48.467 NotebookApp] The Jupyter Notebook is running at:
[I 14:46:48.467 NotebookApp] http://[all ip addresses on your system]:8888/?token=da2f989a57935442f7e08b7dde11472756940a332d2e59a6
[I 14:46:48.467 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:46:48.468 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=da2f989a57935442f7e08b7dde11472756940a332d2e59a6
[I 14:47:17.142 NotebookApp] 302 GET /?token=da2f989a57935442f7e08b7dde11472756940a332d2e59a6 (172.17.0.1) 0.47ms
[I 14:47:25.892 NotebookApp] Creating new notebook in 
[I 14:47:25.904 NotebookApp] Writing notebook-signing key to /home/jupyter/.local/share/jupyter/notebook_secret
[I 14:47:34.193 NotebookApp] Kernel started: 56bbc1cc-23be-4783-8258-a250ebf1666e
__init__
__main__
setgpid( ) failed: Operation not permitted
                   processes may be left dangling...
CASA Version 5.1.1-5  -REL (r40000)
  Compiled on: Mon 2018/01/15 13:35:54 UTC
show_console = False
PYVER        -  2.7
AIPS_DIR     -  /usr/local/casa/
SCRIPT_REPOS -  /usr/local/casa//linux64/lib/python2.7/regressions/
--------------------------------------------------------------------------------
3C129_regression.py			     listvis_regression.py
3C219D_regression.py			     m51_3sim_regression.py
3C219D_test_regression.py		     m51_tpsim_regression.py
3C391polim_regression.py		     maclog_regression.py
3c129_tutorial_regression.py		     nf_regression.py
accum_regression.py			     ngc1333_regression.py
admin					     ngc2403_regression.py
alma-m100-analysis-hpc-regression-tclean.py  ngc2403_tutorial_regression.py
alma-m100-analysis-hpc-regression.py	     ngc4826-mms_tutorial_regression.py
alma-m100-analysis-hpc-tclean.py	     ngc4826_demo.py
alma-m100-analysis-hpc.py		     ngc4826_regression.py
alma-m100-analysis-regression.py	     ngc4826_tutorial.py
alma-m100-analysis.py			     ngc4826_tutorial_regression.py
alma-m100-sd-regression.py		     ngc4826c_regression.py
alma-m100-sd.py				     ngc5921_demo.py
alma-ngc3256-analysis-regression.py	     ngc5921_regression.py
alma-ngc3256-analysis.py		     ngc5921_usecase.py
alma-titan-ephemeris-regression.py	     ngc5921redux_regression.py
alma-titan-ephemeris.py			     ngc7538_regression.py
alma_asdm+reimported-asdm_sf.py		     orion_regression.py
asdm-imexport+analysis_regression.py	     pipelineTest_regression.py
async-segfault_regression.py		     pointing_regression.py
b0319_regression.py			     polcal_20080224_cband.py
backend_demo.py				     polcal_20080224_cband_regression.py
calstat_test_regression.py		     ppdisk2_regression.py
cleanchan_regression.py			     pylabmem_regression.py
cleanhelper_regression.py		     run_orionmos4sim.py
coordsystest_regression.py		     run_polcal_20080224_cband_usecase.py
cvel+clean_test_regression.py		     run_usecase_orions.py
cvel_regression2.py			     sdnewfeatures_b3_tutorial.py
equinox_vis_regression.py		     stokesimagingtest_regression.py
fits-import-export_regression.py	     test_task_cvel.py
g192_regression.py			     test_task_exportasdm.py
h121_regression.py			     testcompsim.py
ic2233_regression.py			     testcube2_regression.py
imagepoltest_regression.py		     tests
imagetest_regression.py			     time_then_chan_avg.py
jupiter6cm_caldemo.py			     unit_tests.py
jupiter6cm_demo.py			     vla_uvfits_line_sf.py
jupiter6cm_flagdemo.py			     wf_regression.py
jupiter6cm_imagingdemo.py		     wideband.py
jupiter6cm_poldemo.py			     wideband_regression.py
jupiter6cm_usecase.py			     widebandmosaic_regression.py
l02d_regression.py			     wproj3ddat_regression.py
leo2pt_regression.py			     wproject.py
listcal_regression.py			     wproject_regression.py
--------------------------------------------------------------------------------
___________________________________________________________________
    For help use the following commands:
    tasklist               - Task list organized by category
    taskhelp               - One line summary of available tasks
    help taskname          - Full help for task
    toolhelp               - One line summary of available tools
    help par.parametername - Full help for parameter name
___________________________________________________________________
ERROR: falied to create an instance of IPython.Shell.IPShell 7
[I 14:47:36.177 NotebookApp] Adapting to protocol v5.1 for kernel 56bbc1cc-23be-4783-8258-a250ebf1666e
[W 14:47:36.220 NotebookApp] 404 GET /static/components/codemirror/mode/Casa/Casa.js?v=20180516144648 (172.17.0.1) 8.72ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=casapy
```

**Comment by aardk** [comment]
Hi Rachael,

Cool that you got X11 to work in the Docker container, I don't have access to a mac myself so I haven't been able to any testing on OSX.  I fixed your docker invocation, this should get local data to work:
docker run --rm -p 8888:8888 -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$ip:0 -v /Users/rachael/Desktop/emerlin-casa-jupyter/data:/home/jupyter/data penngwyn/jupytercasa /bin/sh -c "jupyter notebook"

Actually it is also possible to run Jupyter-casa without X11, although, of course, this would mean that you can no longer run casa tasks in GUI mode. The incantation for this is:
docker run --rm -p 8888:8888 -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=:102 -v /Users/rachael/Desktop/emerlin-casa-jupyter/data:/home/jupyter/data penngwyn/jupytercasa /bin/sh -c "Xvfb :102 -ac & jupyter notebook"

I'll update the manual, when I wrote it I wasn't aware of Xvfb.

I think that your problems with Singularity are most likely caused by the presence of a .casarc file in your home directory.

**Comment by rainsworth** [comment]
Hi @aardk,

Thank you so much for your reply, that all worked like a charm. I had realised my path to data error this morning 🤦‍♀️ 

Docker is now working on mac following:
```
open -a XQuartz
ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
xhost + $ip
docker run --rm -p 8888:8888 -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$ip:0 -v /local/path/to/data/:/home/jupyter/data penngwyn/jupytercasa /bin/sh -c "jupyter notebook"
```

and removing the .casarc file worked for Singularity.

Cheers!
